### ISSUE TITLE
Issue with escaped chain terminators

### ISSUE THREAD

**Issue by wzr** [nyx0/YaraSyntax#1]
Hello there, first of all thanks a lot for the plug in, it's quite handy.

I found an issue: the following rules break the coloring in line $c, on the escaped (with backslash) doublequote and forward slash respectively:

rule rule1 : tag_1 tag_2
{
    meta:
        desc = "test"

```
strings:
    $a          =   "###TEST 1###"
    $b          =   "###TEST 2'###"
    $c          =   "echo THIS LINE \"aaa"
    $d          =   "TEST3"
condition:
    all of them
```

}

The same happens with regexes:

rule rule1 : tag_1 tag_2
{
    meta:
        desc = "test"

```
strings:
    $a          =   "###TEST 1###"
    $b          =   "###TEST 2'###"
    $c          =   /echo THIS LINE \/aaa/
    $d          =   /TEST3\/afdasdf/
condition:
    all of them
```

}

is it fixable?

TIA.

**Comment by nyx0** [comment]
Hello, thanks for your help it's appreciate, I already seen this issue but didn't took the time to fix it.
You can made a PR if you want, otherwise I'll fix it as soon as can.
